Algoritmo "intervalo"
// Disciplina   : [PA]
// Professor   : Edilma Bindá
// Autor(a)    : Ryllary
// Data atual  : 25/05/2023
Var
// Seção de Declarações das variáveis
num: real

//ENTRADA
Inicio
escreval ("numero")
leia (num)

//PROCESSAMENTO E SAIDA
se num > 100 entao
e
se num < 200 entao
escreval ("está entre! UwU ")
senao
escreval ("não está entre! :)")
fimse
fimse
Fimalgoritmo