Algoritmo "DolarparaReal"
// Disciplina   : PA
// Professor   : Edilma Binda
// Autor(a)    : Ryllary Barroso
// Data atual  : 30/03/23
Var
dc, realdin, dq : real

// ENTRADA
Inicio
escreval ("Digite a cotação do dólar: ")
leia (dc)
escreval ("Digite a quantidade de Dólares: ")
leia (dq)

// PROCESSAMENTO
realdin <- dq * dc

// SAÍDA
escreval ("O valor em real é: ", realdin)

Fimalgoritmo