Algoritmo "Carro"
// Disciplina   : [PA]
// Professor   : Edilma Bindá
// Autor(a)    : Ryllary
// Data atual  : 25/05/2023
Var
// Seção de Declarações das variáveis 

idade: real

//ENTRADA
Inicio
escreval ("começou!")
escreval ("digite sua idade")
leia (idade)

//PROCESSAMENTO E SAIDA
se idade >= 18 então
escreval ("ok, pode passar")
senao
escreval ("você não pode dirigir")
fimse

Fimalgoritmo