Algoritmo "temp"
// Disciplina   : [PA]
// Professor   : Edilma Bindá
// Autor(a)    : Ryllary
// Data atual  : 25/05/2023
Var
// Seção de Declarações das variáveis
temp: real

//ENTRADA
Inicio
escreval ("temperatura")
leia (temp)

//PROCESSAMENTO E SAIDA
se temp < 20 então
escreval ("está frio! UwU ")
senao
se temp < 25 então
escreval ("está normal! ;3")
senao
escreval ("está quente! ;)")
fimse
fimse
Fimalgoritmo