Algoritmo "maior que dez"
// Disciplina   : [PA]
// Professor   : Edilma Bindá
// Autor(a)    : Ryllary
// Data atual  : 25/05/2023
Var
// Seção de Declarações das variáveis 

num: real

//ENTRADA
Inicio
escreval ("começou!")
escreval ("digite o número")
leia (num)

//PROCESSAMENTO E SAIDA
se num > 10 então
escreval ("ok, está correto")
senao
escreval ("está incorreto")
fimse

Fimalgoritmo